In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/sample_data/Iris.csv')
print(dataset)

      Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]


In [3]:
dataset['Species'] = dataset['Species'].astype('category')
dataset['Encoded_Category'] = dataset['Species'].cat.codes
print(dataset)

      Id  SepalLengthCm  ...         Species  Encoded_Category
0      1            5.1  ...     Iris-setosa                 0
1      2            4.9  ...     Iris-setosa                 0
2      3            4.7  ...     Iris-setosa                 0
3      4            4.6  ...     Iris-setosa                 0
4      5            5.0  ...     Iris-setosa                 0
..   ...            ...  ...             ...               ...
145  146            6.7  ...  Iris-virginica                 2
146  147            6.3  ...  Iris-virginica                 2
147  148            6.5  ...  Iris-virginica                 2
148  149            6.2  ...  Iris-virginica                 2
149  150            5.9  ...  Iris-virginica                 2

[150 rows x 7 columns]


In [26]:
X = dataset.iloc[:,1:5].values
Y = dataset.iloc[:,-1].values

In [27]:
print(X.shape, Y.shape)

(150, 4) (150,)


In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)


In [29]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

[2 0 0 0 0 2 2 0 1 0 2 0 0 2 1 0 1 0 2 2 1 0 1 1 1 2 1 0 0 0] [2 0 0 0 0 2 2 0 1 0 2 0 0 2 1 0 2 0 2 2 1 0 1 1 1 2 1 0 0 0]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [30]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
Accuracy:
 0.9666666666666667
Precision:
 [1.         1.         0.88888889]
Recall:
 [1.    0.875 1.   ]


In [31]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
Accuracy:
 0.9666666666666667


In [32]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]
Accuracy:
 0.9333333333333333


In [33]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]
Accuracy:
 0.9333333333333333
