# Numpy examples

In [72]:
import numpy as np

In [2]:
a=np.array([1,2,3]) # One dimensional array
a

array([1, 2, 3])

In [3]:
a=np.array([(1,2,3),(4,5,6)]) # Two dimensional array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a=np.zeros(3) # 1D array of length of size of parameter given all values 0(float)
a

array([0., 0., 0.])

In [6]:
a=np.ones((3,4)) # 3x4 array with all values 1(float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a[2][3]

1.0

In [9]:
a=np.eye(5) # 5x5 array of 0 with 1 on diagonal (Identity matrix)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a=np.linspace(0,100,6) # Array of 6 evenly divided values from 0 to 100
a

array([  0.,  20.,  40.,  60.,  80., 100.])

In [11]:
a=np.arange(0,10,3) # Array of values from 0 to less than 10 with step 3
a

array([0, 3, 6, 9])

In [12]:
a=np.full((3,3),1) # 2x3 array with all values 1
a 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
a=np.random.rand(4,5) # 4x5 array of random floats between 0–1
a

array([[0.93456968, 0.74737508, 0.04685406, 0.77589504, 0.49638457],
       [0.24972133, 0.48670848, 0.89109999, 0.37033209, 0.10508936],
       [0.33500728, 0.48958688, 0.24296763, 0.71149038, 0.4313153 ],
       [0.33487817, 0.65125971, 0.80714021, 0.61085049, 0.2647099 ]])

In [14]:
a=np.random.rand(3,3)*100 # 6x7 array of random floats between 0–100
a

array([[53.87468868, 31.42981734, 69.03052253],
       [34.83497281, 88.26768647, 35.70090051],
       [21.34521913, 70.50382471, 62.28381456]])

In [15]:
a=np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4
a

array([[3, 2, 0],
       [1, 4, 2]])

In [16]:
a.size # Returns number of elements in a

6

In [17]:
a.shape # Returns dimensions of a (rows,columns)

(2, 3)

In [18]:
a.dtype # Returns type of elements in a

dtype('int32')

In [20]:
a.astype('float') # Convert a elements to type float

array([[3., 2., 0.],
       [1., 4., 2.]])

In [22]:
print(type(a))
a=a.tolist() # Convert a to a Python list
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [23]:
np.info(np.eye) # View documentation for np.eye


 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [25]:
np.eye(3,dtype=int, k=1)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [27]:
b=np.copy(a) # Copies a to new memory
b

array([[3, 2, 0],
       [1, 4, 2]])

In [31]:
b.view('int') # Creates view of arr elements with type int

array([[3, 2, 0],
       [1, 4, 2]])

In [32]:
b.sort() # Sorts arr (rowwise if 2D)
b

array([[0, 2, 3],
       [1, 2, 4]])

In [34]:
a=np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4
a

array([[2, 3, 4],
       [1, 3, 2]])

In [35]:
a
a.sort(axis=0) # Sorts specific axis of a(here 0th)
a

array([[1, 3, 2],
       [2, 3, 4]])

In [37]:
b=a.flatten() # Flattens 2D array b to 1D
b

array([1, 3, 2, 2, 3, 4])

In [39]:
c=a.T # Transposes a (rows become columns and vice versa)
c

array([[1, 2],
       [3, 3],
       [2, 4]])

In [43]:
d=c.reshape(1,-1) # Reshapes a to 1 rows, -1 columns without changing data
d

array([[1, 2, 3, 3, 2, 4]])

In [44]:
d=c.reshape(-1,1) 
d

array([[1],
       [2],
       [3],
       [3],
       [2],
       [4]])

In [49]:
a

array([[1, 3, 2],
       [2, 3, 4]])

In [50]:
b

array([1, 3, 2, 2, 3, 4])

In [51]:
np.append(b,5) # Appends values to end of arr

array([1, 3, 2, 2, 3, 4, 5])

In [54]:
np.insert(b,2,0) # Inserts values into arr before index 2(eliminates the last one)

array([1, 3, 0, 2, 2, 3, 4])

In [55]:
a

array([[1, 3, 2],
       [2, 3, 4]])

In [58]:
x=np.delete(a,1,axis=0) # Deletes row on index 1 of arr
x

array([[1, 3, 2]])

In [60]:
y=np.delete(a,1,axis=1) # Deletes column on index 1 of arr
y

array([[1, 2],
       [2, 4]])

In [62]:
a=np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4
a

array([[4, 1, 0],
       [2, 1, 3]])

In [63]:
b=np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4
b

array([[3, 4, 4],
       [3, 3, 1]])

In [64]:
np.concatenate((b,a),axis=0) # Adds a as rows to the end of b

array([[3, 4, 4],
       [3, 3, 1],
       [4, 1, 0],
       [2, 1, 3]])

In [66]:
p=np.concatenate((b,a),axis=1) # Adds a as columns to the end of b

In [67]:
p

array([[3, 4, 4, 4, 1, 0],
       [3, 3, 1, 2, 1, 3]])

In [69]:
np.split(p,2) # Splits arr into 2 sub-arrays

[array([[3, 4, 4, 4, 1, 0]]), array([[3, 3, 1, 2, 1, 3]])]

In [70]:
np.hsplit(p,1) # Splits arr horizontally on the 5th index


[array([[3, 4, 4, 4, 1, 0],
        [3, 3, 1, 2, 1, 3]])]