In [1]:
# lists are slow in python as compared to numpy arays
# lists stores data in a compact way
# lists stores data of differnt type while numpy arrays stores data of same type
# numpy is a library that adds support to the large multi dimensional arrays and matrices along with a large collection of high
# -level mathematical functions to operate on these arrays

In [2]:
import numpy as np

In [4]:
# create a numpy array

l1 = [1,2,3]
a = np.array(l1)           # we can pass a list
print(a, type(a), a.dtype)

t = (5,6,7,8)
c = np.array(t)            # we can pass a tuple as well
print(c, type(c))

l2 = [1,2,'a']             # if anyone element of list is string then np array will convert all the elements
b = np.array(l2)
print(b, type(b), b.dtype)

print(np.zeros(10))        # by default it will create the aaray with 0 as an element in float format
print(np.zeros(10, int))   # we can also pass the data type of zeros

print(np.ones(5))
print(np.ones(5, str))

[1 2 3] <class 'numpy.ndarray'> int32
[5 6 7 8] <class 'numpy.ndarray'>
['1' '2' 'a'] <class 'numpy.ndarray'> <U11
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1.]
['1' '1' '1' '1' '1']


In [5]:
# to create a 2D array or 3D array

a = np.zeros((2,3), int)
a[0] = "1"               # it will automatically typecast string into int since we have provided the datatype in the beginning 
print(a, end="\n\n\n")

b = np.ones((2,3,4), int)
print(b)

[[1 1 1]
 [0 0 0]]


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [23]:
# to access the data from an array we can do slicing like in lists 

In [25]:
b.shape   # v.important as it tells the dimension of an array

(2, 3, 4)

In [29]:
# very interesting function to access the subarray/submatrix from an array

l = [[1,2,3,4,5],[6,7,8,9,10]]
a = np.array(l)

print(a[:])          # sb kuch dedo
print(a[: , 0])      # gives the elements of all rows and 0th column 
print(a[0:1 , 1:3])  # gives the elements of 0th row and column from 1 to 2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 6]
[[2 3]]


In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a = np.array([1,2,3])
a.shape

(3,)

In [4]:
# numpy operations

# numpy arrays perform element wise opeartion

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+2)
print(a+b)
print(a*2)
print(a*b)
print(a**2)
print(a**b)

[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]
[1 4 9]
[  1  32 729]


In [6]:
a = np.array([[1,2,3],[1,7,3]])
print(a.mean())
print(a.sum())

2.8333333333333335
17


In [46]:
# calculating distance between the points
import math
a = np.array([1,2,3])
b = np.array([4,5,6])

d = ((a-b)**2).sum()
d = math.sqrt(d)
print(d)

5.196152422706632


In [48]:
# calculating deviation from mean value

x = np.array([1,2,3])
((x-x.mean())**2).sum()

2.0

In [50]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

a1.dot(a2)                # to calculate the dot product

array([[ 70, 100],
       [150, 220]])

In [52]:
a1 = np.array([0,1,2,3])
a2 = np.array([2,3,4,5])

a1.dot(a2)      

26

In [64]:
# reshape() function returns an array containing the same data with a new shape.

l = [[1,2,3,4],[5,6,7,8]]
a= np.array(l)

n = a.reshape(4,2)
print(n)

n =a.reshape(-1,1)
print(n)

n =a.reshape(1,-1)
print(n)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]


In [73]:
a = np.array([[1,2,3],[4,5,6]])

print(np.sum(a[0]))
print(np.sum(a[:,2]))
print(np.sum(a[1,0:2]))
print(np.sum(a,axis=0))  #column wise sum
print(np.sum(a,axis=1))  #row wise sum

6
9
9
[5 7 9]
[ 6 15]


In [74]:
# Numpy also has lots of ways to create random number arrays:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

np.random.rand(2)

array([0.06302121, 0.35187764])

In [75]:
 np.random.rand(5,5)

array([[0.12863172, 0.34210798, 0.67839496, 0.28661509, 0.64419187],
       [0.4746834 , 0.77357169, 0.05467986, 0.00507823, 0.95733932],
       [0.46914244, 0.55453032, 0.51705681, 0.64481522, 0.65148976],
       [0.68214225, 0.36055301, 0.36024092, 0.02743101, 0.65780598],
       [0.6505887 , 0.56068257, 0.06164566, 0.19842926, 0.36163937]])

In [76]:
# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

np.random.randn(2)

array([-0.95542663, -1.93365416])

In [77]:
 np.random.randn(5,5)

array([[ 0.17413398, -0.09312541,  0.13277374, -1.03304525, -1.11769778],
       [-0.20733095,  0.50380104, -0.00394683, -1.38442798,  0.76495558],
       [-1.95678578,  2.03613253,  2.68019942, -0.29749535,  0.88645082],
       [ 1.49505225, -0.74739336,  1.51749711,  2.12004131, -1.64266193],
       [ 1.77466367, -0.27267443, -1.09979213, -0.16492723,  0.60984943]])

In [78]:
# Return random integers from low (inclusive) to high (exclusive).

np.random.randint(1,100)

89

In [9]:
# Following will randomly sample 10 values in the interval [1, 100)

print(np.random.randint(1,100,10))
print(np.random.randint(1,100,(10,2)))

[18 68 57 90 14 59 73 21 97 52]
[[19 71]
 [64 91]
 [52 43]
 [31 11]
 [25 59]
 [44 81]
 [69 76]
 [16 73]
 [38 12]
 [26 56]]


In [80]:
# Let's discuss some useful attributes and methods or an array:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
ranarr

array([17, 21, 33, 27, 30, 48, 13, 46,  8, 23])

In [13]:
# to measure the cell execution time use %%time

%%time
for i in range(0,1000):
    i = i + 1
print(i)

UsageError: Line magic function `%%time` not found.


In [14]:
# shortcuts of jupyter notebook

#  tab  :  it will show all the methods or library available
#  shift + tab  :  show documentation of a function