# NumPy
NumPy is a Python package. It stands for Numerical Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## What are arrays?
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

## Importing NumPy

In [1]:
import numpy as np

## The basics

In [2]:
#creating an array
a = np.array([4,5,7,2,8])
print(a)

[4 5 7 2 8]


In [3]:
#get dimension
a.ndim

1

In [4]:
#get shape
a.shape

(5,)

In [5]:
#get data type of elements
a.dtype

dtype('int32')

In [6]:
#get number of elements
a.size

5

## Converting list to numpy array

In [7]:
my_list = [4,6,3,8]
arr = np.array(my_list)

In [8]:
print(arr)

[4 6 3 8]


In [9]:
type(arr)

numpy.ndarray

## Multi-dimensional array

In [10]:
#creating a multi-dimensional array
md_arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(md_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Accessing/Changing specific elements, rows, columns, etc.

### One dimensional array

In [11]:
arr

array([4, 6, 3, 8])

In [12]:
#get a specific element
arr[2]

3

In [13]:
#get elements in a range of indices [i1:i2] - i1:inclusive and i2:exclusive
arr[0:2]

array([4, 6])

### Multi-dimensional array

In [14]:
md_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Slicing arrays:

In [15]:
#get a specific element [r, c]
md_arr[1, 2]

6

In [16]:
#get a specific row
md_arr[2,:]

array([7, 8, 9])

In [17]:
#get a specific column
md_arr[:,1]

array([2, 5, 8])

In [18]:
md_arr[0,1] = 15

md_arr[:, 1] = [10]
print(md_arr)

[[ 1 10  3]
 [ 4 10  6]
 [ 7 10  9]]


#### Concatenation of arrays

In [19]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

### Arithmetic Operations

In [20]:
#add two arrays
add = np.add(x,y)
add

array([4, 4, 4])

In [21]:
#subtract two arrays
sub =np.subtract(x,y)
sub

array([-2,  0,  2])

In [22]:
#unary negation
neg=np.negative(x)
neg

array([-1, -2, -3])

In [23]:
#multiply two arrays
prod = np.multiply(x,y)
prod

array([3, 4, 3])

In [24]:
#divide two arrays
div = np.divide(x,y)
div

array([0.33333333, 1.        , 3.        ])

In [25]:
#floor division of two arrays
floordiv = np.floor_divide(x,y)
floordiv

array([0, 1, 3])

In [26]:
#exponentiation
power = np.power(2,3)
power

8

In [27]:
#modulus
mod = np.mod(9,4)
mod

1

## Inbuilt Functions

### arange : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

In [28]:
#elements will range from 0 to 14
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
#elements will range from 2 to 15(exclusive) with data type as float
np.arange(2, 15, dtype=float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [30]:
#elements will range from 1 to 15(exclusive) with an increment of 3 after each element
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

### linspace : will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values
linspace(start, stop, step) - stop is included

In [31]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.linspace(1., 4., 6, False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

### shape : returns shape (row, column) of an array 
### reshape : shapes an array without changing data of array

In [33]:
A = np.array([[1,2,3],
             [4,5,6]
             ])

In [34]:
A.shape

(2, 3)

In [35]:
B = np.array([
        [12, 11, 10],
        [9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]
    
])

In [36]:
B.shape

(4, 3)

In [37]:
B.reshape(3, 4)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### zeros : returns a new array of given shape and type, with zeros

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### ones :  returns a new array of given shape and type, with ones.

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.ones((5, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### empty : returns a new array of given shape and type, with random values.

In [44]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.empty((3,3), dtype=int)

array([[        0,         0, 279203168],
       [      267, 279204048,       267],
       [279202128,       267,   7929957]])

### identity : returns an identity matrix i.e. a square matrix with ones on the main diagonal

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### eye : returns a 2-D array with 1's as the diagonal and 0's elsewhere

In [48]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [49]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.eye(8,4,k=-3, dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

### random

In [51]:
np.random.random(size=3)

array([0.3812388 , 0.03651375, 0.34331775])

In [52]:
np.random.normal(size=2)

array([ 0.61284422, -0.07029641])

In [53]:
np.random.rand(2,5)

array([[0.10587568, 0.14647444, 0.01860027, 0.78634316, 0.74404556],
       [0.19103123, 0.03814603, 0.08133144, 0.59476043, 0.82063691]])

### copy : returns a copy of the array

In [54]:
a = np.array([2,5,6])
b = a.copy()
b[1]=8
print(b)

[2 8 6]


## Linear Algebra

In [55]:
A=np.array([[1,2,3], 
           [4, 5, 6],
           [7, 8, 9]
           ])

In [56]:
B=np.array([[2,2], 
           [8,6],
           [3,4]
           ])

In [57]:
A.dot(B)

array([[ 27,  26],
       [ 66,  62],
       [105,  98]])

In [58]:
#same as A.dot(B)
A@B

array([[ 27,  26],
       [ 66,  62],
       [105,  98]])

In [59]:
#transpose
B.T

array([[2, 8, 3],
       [2, 6, 4]])

## Summary Statistics

In [60]:
#one dimensional array
a = np.array([4,6,3,2,7])

In [61]:
#sum of elements
a.sum()

22

In [62]:
#standard deviation
a.std()

1.8547236990991407

In [63]:
#variance
a.var()

3.44

In [64]:
#multi dimensional array
A = np.array([
    [1,5,6],
    [4,2,6]
])

In [65]:
A.sum()

24

In [66]:
A.mean()

4.0

In [67]:
A.std()

1.9148542155126762

In [68]:
#sum of elements of columns
A.sum(axis=0)

array([ 5,  7, 12])