# NumPy
NumPy is a Python package. It stands for Numerical Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## What are arrays?
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

## Importing NumPy

In [1]:
import numpy as np

## The basics

In [7]:
#creating an array
a = np.array([4,5,7,2,8])
print(a)

[4 5 7 2 8]


In [8]:
#get dimension
a.ndim

1

In [9]:
#get shape
a.shape

(5,)

In [10]:
#get data type of elements
a.dtype

dtype('int32')

In [11]:
#get number of elements
a.size

5

## Converting list to numpy array

In [2]:
my_list = [4,6,3,8]
arr = np.array(my_list)

In [3]:
print(arr)

[4 6 3 8]


In [4]:
type(arr)

numpy.ndarray

## Multi-dimensional array

In [12]:
#creating a multi-dimensional array
md_arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(md_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Accessing/Changing specific elements, rows, columns, etc.

### One dimensional array

In [14]:
arr

array([4, 6, 3, 8])

In [13]:
#get a specific element
arr[2]

3

In [16]:
#get elements in a range of indices [i1:i2] - i1:inclusive and i2:exclusive
arr[0:2]

array([4, 6])

### Multi-dimensional array

In [17]:
md_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#get a specific element [r, c]
md_arr[1, 2]

6

In [22]:
#get a specific row
md_arr[2,:]

array([7, 8, 9])

In [21]:
#get a specific column
md_arr[:,1]

array([2, 5, 8])

In [24]:
md_arr[0,1] = 15

md_arr[:, 1] = [10]
print(md_arr)

[[ 1 10  3]
 [ 4 10  6]
 [ 7 10  9]]


## Inbuilt Functions

### arange : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

In [25]:
#elements will range from 0 to 14
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
#elements will range from 2 to 15(exclusive) with data type as float
np.arange(2, 15, dtype=float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [28]:
#elements will range from 1 to 15(exclusive) with an increment of 3 after each element
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

### linspace : will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values
linspace(start, stop, step) - stop is included

In [38]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.linspace(1., 4., 6, False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

### shape : returns shape (row, column) of an array 
### reshape : shapes an array without changing data of array

In [30]:
A = np.array([[1,2,3],
             [4,5,6]
             ])

In [31]:
A.shape

(2, 3)

In [35]:
B = np.array([
        [12, 11, 10],
        [9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]
    
])

In [36]:
B.shape

(4, 3)

In [37]:
B.reshape(3, 4)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### zeros : returns a new array of given shape and type, with zeros

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### ones :  returns a new array of given shape and type, with ones.

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.ones((5, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### empty : returns a new array of given shape and type, with random values.

In [47]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [49]:
np.empty((3,3), dtype=int)

array([[         1,          1,          0],
       [1936682280,        344,          0],
       [  16777984,        459,  573142131]])

### identity : returns an identity matrix i.e. a square matrix with ones on the main diagonal

In [50]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### eye : returns a 2-D array with 1's as the diagonal and 0's elsewhere

In [54]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [55]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.eye(8,4,k=-3, dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

### random

In [58]:
np.random.random(size=3)

array([0.96844061, 0.04042306, 0.287759  ])

In [59]:
np.random.normal(size=2)

array([-1.68800733,  0.69039249])

In [60]:
np.random.rand(2,5)

array([[0.88905109, 0.23563943, 0.57782012, 0.74340422, 0.88435015],
       [0.79799881, 0.71703718, 0.7145446 , 0.54194783, 0.76422077]])

### copy : returns a copy of the array

In [62]:
a = np.array([2,5,6])
b = a.copy()
b[1]=8
print(b)

[2 8 6]


## Linear Algebra

In [63]:
A=np.array([[1,2,3], 
           [4, 5, 6],
           [7, 8, 9]
           ])

In [64]:
B=np.array([[2,2], 
           [8,6],
           [3,4]
           ])

In [65]:
A.dot(B)

array([[ 27,  26],
       [ 66,  62],
       [105,  98]])

In [66]:
#same as A.dot(B)
A@B

array([[ 27,  26],
       [ 66,  62],
       [105,  98]])

In [67]:
#transpose
B.T

array([[2, 8, 3],
       [2, 6, 4]])

## Summary Statistics

In [68]:
#one dimensional array
a = np.array([4,6,3,2,7])

In [69]:
#sum of elements
a.sum()

22

In [70]:
#standard deviation
a.std()

1.8547236990991407

In [71]:
#variance
a.var()

3.44

In [76]:
#multi dimensional array
A = np.array([
    [1,5,6],
    [4,2,6]
])

In [77]:
A.sum()

24

In [78]:
A.mean()

4.0

In [79]:
A.std()

1.9148542155126762

In [80]:
#sum of elements of columns
A.sum(axis=0)

array([ 5,  7, 12])